# Generated by Django 4.1.4 on 2022-12-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MobileRecharge', '0002_oprators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oprators',
            name='oprator_type',
            field=models.CharField(choices=[['CDMA', 'GSM']], default='', max_length=100),
        ),
    ]
