# Generated by Django 4.1.4 on 2022-12-10 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MobileRecharge', '0004_alter_oprators_oprator_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plan_state', models.CharField(blank=True, default='', max_length=100)),
                ('plan_oprator', models.CharField(blank=True, default='', max_length=100)),
                ('plan_name', models.CharField(blank=True, default='', max_length=100)),
                ('plan_category', models.CharField(blank=True, default='', max_length=100)),
                ('plan_price', models.CharField(blank=True, default='', max_length=100)),
                ('plan_validity', models.CharField(blank=True, default='', max_length=100)),
                ('plan_details', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterModelOptions(
            name='oprators',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='oprators',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oprators',
            name='oprator_type',
            field=models.TextField(blank=True, choices=[('CDMA', 'CDMA'), ('GSM', 'GSM'), ('GSM/CDMA', 'GSM/CDMA')], null=True),
        ),
    ]
