# Generated by Django 4.1.4 on 2022-12-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileRecharge', '0008_history_amount_alter_oprators_oprator_state_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
